export { default as SignUp } from "./SignUp";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Home } from "./Home";
export { default as App } from "./menu-maker";
export { default as AppUser } from "./menu-maker-user";
export { default as HomeUser } from "./HomeUser";
export { default as HomeAdmin } from "./HomeAdmin";
export { default as Categories} from "./categories-maker";
export { default as PaymentsHome } from "./PaymentsHome";
export { default as FeedbackHome } from "./FeedbackHome";
export { default as Courses } from "./course-maker";
export { default as CoursesUser } from "./course-maker-user";
export { default as Menu } from "./show-menu";
